name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - command: check-lint
          - command: test
          - command: build-debug
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Maximize Runner Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/share/powershell

      - uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      - name: Cache Gradle
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            .gradle-home/caches
            .gradle-home/wrapper
          key: v1-${{ runner.os }}-gradle-gymbro-ci-${{ hashFiles('flake.nix', 'flake.lock', '**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            v1-${{ runner.os }}-gradle-gymbro-ci-

      - name: Run ${{ matrix.command }}
        run: nix develop .#gymbro-ci --no-update-lock-file --command just ${{ matrix.command }}
